GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/69f271c1139401e42080599e

###

DELETE http://localhost:3001/api/persons/69f268326af85b7fd6a2ee HTTP/1.1

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "terry",
    "number": "111-111-1111"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "blah": "blah, blah, blah"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "a"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "aaa"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "aaa",
    "number": "111-111-124"
}

###

PUT http://localhost:3001/api/persons/69f3b216a70c8e444c4a0336 HTTP/1.1
Content-Type: application/json

{
    "name": "terry",
    "number": "111-111-111"
}

###

PUT http://localhost:3001/api/persons/69f3b216a70c8e444c4a0336 HTTP/1.1
Content-Type: application/json

{
    "name": "terry",
    "number": "111-222-1111"
}

###

GET http://localhost:3001/info
