GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs http/1.1
Content-Type: application/json

{
    "content": "I cannot wait to finish this course for the 2nd time hehe haha hoho",
    "important": true
}

###

POST http://localhost:3001/api/blogs http/1.1
Content-Type: application/json

{
    "title": "arin",
    "author": "arin",
    "url": "arin",
    "likes": 4
}

###

POST http://localhost:3001/api/blogs http/1.1
Content-Type: application/json

{
    
    "author": "arin",
    "likes": 4
}

###

GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs/69f

###

DELETE http://localhost:3001/api/blogs/69fceecf0750adea8ce53143

###

PUT http://localhost:3001/api/blogs/69fcf2c8cd99fb57d3a91d88
Content-Type: application/json

{
    "title": "erci",
    "author": "sparrow",
    "url": "eric_s.com",
    "likes": 4
}

###

PUT http://localhost:3001/api/blogs/69f1409b390c56fba78e7bfe
Content-Type: application/json

{
    "content": "I cannot wait to mess with the new course",
    "important": false
}