GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes http/1.1
Content-Type: application/json

{
    "content": "I cannot wait to finish this course for the 2nd time hehe haha hoho",
    "important": true
}

###

POST http://localhost:3001/api/notes http/1.1
Content-Type: application/json

{
    "content": "I am",
    "important": true
}

###

GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/69f

###

DELETE http://localhost:3001/api/notes/69f380cc16bb6576a1045a3c

###

PUT http://localhost:3001/api/notes/69f1409b390c56fba78e7bfe
Content-Type: application/json

{
    "content": "I cannot wait to finish this course for the 2nd time hehe haha hoho",
    "important": true
}

###

PUT http://localhost:3001/api/notes/69f1409b390c56fba78e7bfe
Content-Type: application/json

{
    "content": "I cannot wait to mess with the new course",
    "important": false
}